### PR TITLE
Temporary workaround for #54

### PR DESCRIPTION
**Pull request by MatthewSteeples**
VS2015 Update 1 appears to break some T4MVC functionality as mentioned in issue #54

### CODE REVIEW

**Comment by davidebbo** [comment]
Fix doesn't seem enough to fix the T4MVC test solution. e.g. it's generating:

```
protected override void WriteFile(System.Web.HttpResponseBase ) { }
```

instead of 

```
protected override void WriteFile(System.Web.HttpResponseBase response) { }
```

Maybe similar hack needed in more places?

**Comment by MatthewSteeples** [comment]
When trying to fix this issue I found there's a lot more places where Name is depended on for the generated code (n is old name, var8 is my test code)
`ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "n", n);
CompiledControllerVirtualMethodOverride(callInfo, n);
ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "", var8);
CompiledControllerVirtualMethodOverride(callInfo, var8);
`

I've made some changes now which unfortunately make this even more of a hack to ensure that the variable name is unique.

**Comment by MatthewSteeples** [comment]
Would appear that that unit test is important, as it's to do with route values and naming. Can't work out a way round that at the moment.

**Comment by kevinkuszyk** [comment]
@MatthewSteeples can we close this [now that the VS update](https://github.com/T4MVC/T4MVC/issues/54#issuecomment-164841688) is out?

**Comment by MatthewSteeples** [comment]
Yep :)

**Pull request closed without merging**
