### PR TITLE
ASP.NET Core - Do NOT merge

### PR DESCRIPTION
**Pull request by cwe1ss**
Hi folks!

https://github.com/T4MVC/T4MVC/issues/65 - Since it seems like noone was brave enough yet to try the migration, I gave it a shot. It doesn't yet work though! :-)

Nevertheless, here's the status in case you want to try it as well!

Since ASP.NET core uses different packages, namespaces and some different classes, I don't think that it's possible to support it with one code. For that reason, I copied the T4MVCExtensions project. (you can use WinMerge to see the changes)

I changed it to compile against the RC1 bits of ASP.NET Core (which means it's still Microsoft.AspNet.\* instead of Microsoft.AspNetCore.*). 

I had to change the following things:
- Namespace System.Web.Mvc -> Microsoft.AspNet.Mvc
- MapRouteArea: now receives IRouteBuilder + string areaName instead of AreaRegistrationContext (I think this doesn't exist anymore)
- copied NameValueCollectionExtensions from System.Web.Mvc
- removed Url.ActionAbsolute (no access to RequestContext from UrlHelper)
- AjaxHelper methods (afaik they don't exist anymore)
- Routes -> IRouteBuilder
- HtmlHelper.Action / HtmlHelper.RenderAction (afaik doesn't exist anymore. ViewComponents?)
- T4Extensions.FileExists / TimestampString (no access to HostingEnvironment)
- some reflection changes to compile against .NET Core

this was a quick&dirty fix and is untested. Which brings me to my problem :-)

I created a new ASP.NET Core web application and copied the T4MVC.tt file. As you've already mentioned, my VStudio also froze on my first attempt to run it. I changed some things in the template (namespaces, ...) and tried it again. This time the template started, however it failed with the following exception:

```
Severity    Code    Description Project File    Line    Suppression State
Error       Running transformation: System.Runtime.Serialization.SerializationException: Type 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItem' in Assembly 'Microsoft.VisualStudio.ProjectSystem.VS.Implementation, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.

Server stack trace: 
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(RuntimeType type)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Remoting.Channels.CrossAppDomainSerializer.SerializeMessageParts(ArrayList argsToSerialize)
   at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage..ctor(IMethodReturnMessage mrm)
   at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage.SmuggleIfPossible(IMessage msg)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)
   at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatchCallback(Object[] args)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at EnvDTE._Solution.FindProjectItem(String FileName)
   at Microsoft.VisualStudio.TextTemplatingE8A802095A8A0101CF6CCE9660A873C5501E7AE5AE4F586D8E1BEEF281D312105B7F869AFEAA0081B3FE11584EF3F5BCF20BE070A47D5D657422D64EE20B33BA.GeneratedTextTransformation.XmlSettings.Init(ITextTemplatingEngineHost host) in c:\C3\Repos\cwe1ss\T4MVC\T4MVCHost.AspNetCore\T4MVC\T4MVC.tt:line 2564
   at Microsoft.VisualStudio.TextTemplatingE8A802095A8A0101CF6CCE9660A873C5501E7AE5AE4F586D8E1BEEF281D312105B7F869AFEAA0081B3FE11584EF3F5BCF20BE070A47D5D657422D64EE20B33BA.GeneratedTextTransformation.XmlSettings.Load[T](ITextTemplatingEngineHost host) in c:\C3\Repos\cwe1ss\T4MVC\T4MVCHost.AspNetCore\T4MVC\T4MVC.tt:line 2541
   at Microsoft.VisualStudio.TextTemplatingE8A802095A8A0101CF6CCE9660A873C5501E7AE5AE4F586D8E1BEEF281D312105B7F869AFEAA0081B3FE11584EF3F5BCF20BE070A47D5D657422D64EE20B33BA.GeneratedTextTransformation.MvcSettings.Load(ITextTemplatingEngineHost host) in c:\C3\Repos\cwe1ss\T4MVC\T4MVCHost.AspNetCore\T4MVC\T4MVC.tt:line 2221
   at Microsoft.VisualStudio.TextTemplatingE8A802095A8A0101CF6CCE9660A873C5501E7AE5AE4F586D8E1BEEF281D312105B7F869AFEAA0081B3FE11584EF3F5BCF20BE070A47D5D657422D64EE20B33BA.GeneratedTextTransformation.TransformText() in c:\C3\Repos\cwe1ss\T4MVC\T4MVCHost.AspNetCore\T4MVC\T4MVC.tt:line 39 T4MVCHost.AspNetCore    c:\C3\Repos\cwe1ss\T4MVC\T4MVCHost.AspNetCore\T4MVC\T4MVC.tt    2564    
```

at this line: `this.ProjectItem = this.DTE.Solution.FindProjectItem(host.TemplateFile);`

I haven't found anything useful about this exception.

Maybe someone could try this as well?!?

### CODE REVIEW

**Comment by kevinkuszyk** [comment]
@cwe1ss thanks for taking a look at this.

I remember hitting some of this issues when we tried to port `T4MvcExtensions` to the `coreclr` for R4MVC.  Unfortunately I couldn't find the code when I looked at the weekend. 

If it was just namespace changes I guess we could use complier directives to bring the correct ones in, but it looks like there are some breaking API changes too.

@davidebbo thoughts?

**Comment by cwe1ss** [comment]
IMO the most important change is that this package will have different nuget dependencies. the current T4MVCExtensions package has a dependency on Microsoft.AspNet.Mvc (>= 3.0.50813.1)
AspNetCore will be a different package. 

This is very similar to packages like Glimpse which have different packages for different target versions (Glimpse.Mvc4, Glimpse.Mvc5, ...). ASP.NET MVC5 will stay current for a long time which means T4MVC should support MVC5 and ASP.NET Core. So I'm afraid there is no way around having multiple packages.

do you prefer to have this discussion here or in #65?

**Comment by kevinkuszyk** [comment]
@cwe1ss it looks like there is a fix for the VS crash.  Let's move the discussion on how we approach this to #65.

**Comment by cwe1ss** [comment]
I'm closing this as it's extremely out of date. Also, theres [R4MVC](https://github.com/T4MVC/R4MVC), so having a Roslyn based system AND a T4 based system is probably a waste of efforts anyway.

**Pull request closed without merging**
