### PR TITLE
Make constant publicly accessible

### PR DESCRIPTION
**Pull request by MatthewSteeples**
We are using T4MVC to register our bundles in MVC, and as part of this we need access to the directory name with a ~ on the front of it, exactly the same as in these constants.

Unless there's a reason for them to stay private we'd like to make use of them

### CODE REVIEW

**Comment by kevinkuszyk** [comment]
Apologies @MatthewSteeples - I missed this one when you opened it.

@davidebbo any objections to merging this?

**Comment by davidebbo** [comment]
Looks good to me. The big diff threw me off at first till I realized the casing change (which makes sense). :shipit:

**Comment by kevinkuszyk** [comment]
@davidebbo can you push a new version to NuGet?

We should probably think about automating pushing to NuGet.  If you think it's a good idea, I'll open a new issue to track this piece of work.

**Comment by davidebbo** [comment]
Ok, I pushed 3.17.6. I also added you as NuGet package owner (you need to approve req).

Yes, some automation wouldn't hurt. Right now, there are too many manual steps to push a new release (e.g. see a36b33574789284b7e3d18ebb0021aaf122e5b7f).

**Pull request merged**
